version: '3.8'

services:
  diyc:
    build: .
    privileged: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
