version: '3.8'

services:
  diyc:
    build: .
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    cap_add:
    - SYS_ADMIN    # clone(), mount(), sethostname() などに必要
    - NET_ADMIN    # ネットワーク名前空間操作に必要
